### ISSUE TITLE
README says use `make`, but Makefile was deleted

### ISSUE THREAD

**Issue by encbar5** [AllStarLink/ASL-Nodes-Diff#1]
The client installation says to run`make install` or `dpkg -i deb/asl-update-node-list_2.0.0-beta.5_all.deb`. Neither of these work.

**Comment by F4HWD** [comment]
I found another solution, you can build a deb package and then install it :

`debuild -b -us -uc`

Go to the parent directory and install the generated package : 

`cd ..`
`sudo dpkg -i asl-update-node-list_2.0.0-beta.5-1_all.deb`

**Comment by encbar5** [comment]
That's fine but the readme still needs to be updated.
